#
# Copyright (C) 2020 IBM Corporation.
#
# Authors:
# Frederico Araujo <frederico.araujo@ibm.com>
# Teryl Taylor <terylt@ibm.com>
#
version: "3.5"
services:
  sf-processor:
    container_name: sf-processor
    image: sysflowtelemetry/sf-processor:latest
    privileged: true
    volumes:
      - socket-vol:/sock/
    environment:
      FILE_PATH: /sock/sysflow.sock
      POLICYENGINE_MODE: alert
      EXPORTER_TYPE: telemetry
      EXPORTER_SOURCE: ${HOSTNAME}
      EXPORTER_EXPORT: terminal
      EXPORTER_HOST: localhost
      EXPORTER_PORT: 514
  sf-collector:
    container_name: sf-collector
    image: sysflowtelemetry/sf-collector:latest
    depends_on:
      - "sf-processor"
    privileged: true
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock 
      - /dev:/host/dev 
      - /proc:/host/proc:ro 
      - /boot:/host/boot:ro 
      - /lib/modules:/host/lib/modules:ro 
      - /usr:/host/usr:ro
      - /mnt/data:/mnt/data
      - socket-vol:/sock/
      - ./resources/traces:/tests/traces
    environment:
      EXPORTER_ID: local
      NODE_IP: "127.0.0.1"
      FILTER: "container.type!=host and container.name!=sf-collector and container.name!=sf-processor" 
      INTERVAL: 300 
      SOCK_FILE: /sock/sysflow.sock
volumes:
  socket-vol:
